### ISSUE TITLE
Simple typo in readme

### ISSUE THREAD

**Issue by JuanGongora** [learn-co-curriculum/js-basics-variables-lab#3]
Typo on line 73 of README.md:

`Here the test is telling us that the tests that come **afterwords** will be about`

Should be:

`Here the test is telling us that the tests that come **afterwards** will be about`

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
